CREATE TYPE event_category AS ENUM (
    'Game',
    'Video',
    'Other'
);

CREATE TABLE retrack_events (
    event_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_name TEXT NOT NULL,
    event_type event_category DEFAULT 'Other',
    relevant_date DATE
);